[plugins."io.containerd.grpc.v1.cri".registry.mirrors."10.249.190.44:5000"]
  endpoint = ["http://10.249.190.44:5000"]
[plugins."io.containerd.grpc.v1.cri".registry.configs."10.249.190.44:5000".tls]
  insecure_skip_verify = true